# Generated by Django 5.1.6 on 2025-03-12 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
                ("description", models.TextField(max_length=1000)),
                ("location", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[("Local", "Local"), ("National", "National")],
                        default="Local",
                        max_length=100,
                    ),
                ),
                ("approved", models.BooleanField(default=False)),
                ("created_by", models.CharField(max_length=100)),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("АСМБ София", "АСМБ София"),
                            ("АСМБ СУ", "АСМБ СУ"),
                            ("АСМБ Варна", "АСМБ Варна"),
                            ("АСМ Пловдив", "АСМ Пловдив"),
                            ("АСМБ Бургас", "АСМБ Бургас"),
                            ("АСМБ Плевен", "АСМБ Плевен"),
                            ("АСМБ Стара Загора", "АСМБ Стара Загора"),
                        ],
                        default="АСМБ СУ",
                        max_length=100,
                    ),
                ),
                ("poster", models.ImageField(blank=True, null=True, upload_to="media")),
            ],
        ),
        migrations.CreateModel(
            name="FavouriteEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_by",
                        to="events.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "event")},
            },
        ),
    ]
