# Generated by Django 5.1.6 on 2025-03-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.CharField(default='Valio', max_length=100),
            preserve_default=False,
        ),
    ]
