# Generated by Django 5.1.6 on 2025-03-15 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_committee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"permissions": [("can_approve_events", "Can approve event")]},
        ),
    ]
