# Generated by Django 5.1.6 on 2025-03-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
