# Generated by Django 5.1.6 on 2025-03-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_created_by_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='branch',
            field=models.CharField(choices=[('АСМБ София', 'АСМБ София'), ('АСМБ СУ', 'АСМБ СУ'), ('АСМБ Варна', 'АСМБ Варна'), ('АСМ Пловдив', 'АСМ Пловдив'), ('АСМБ Бургас', 'АСМБ Бургас'), ('АСМБ Плевен', 'АСМБ Плевен'), ('АСМБ Стара Загора', 'АСМБ Стара Загора')], default='АСМБ СУ', max_length=100),
        ),
    ]
