# Generated by Django 5.1.6 on 2025-03-05 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_by_fk',
        ),
    ]
