# Generated by Django 5.1.6 on 2025-03-12 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="background_picture",
        ),
    ]
