# Generated by Django 5.1.6 on 2025-03-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('National Member Organization President', 'National Member Organization President'), ('Vise President External Affairs', 'Vise President External Affairs'), ('Vise President External Internal', 'Vise President External Internal'), ('PRnC', 'PRnC'), ('Neo-In', 'Neo-In'), ('Neo-Out', 'Neo-Out'), ('Nore-In', 'Nore-In'), ('Nore-Out', 'Nore-Out'), ('Nome', 'Nome'), ('NPO', 'NPO'), ('Nora', 'Nora'), ('NorP', 'NorP'), ('Member', 'Member')], default='Member', max_length=100),
        ),
    ]
