# Generated by Django 5.1.6 on 2025-03-05 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
