# Generated by Django 5.1.6 on 2025-03-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventreport",
            name="branch",
            field=models.CharField(
                choices=[
                    ("АСМБ София", "АСМБ София"),
                    ("АСМБ СУ", "АСМБ СУ"),
                    ("АСМБ Варна", "АСМБ Варна"),
                    ("АСМ Пловдив", "АСМ Пловдив"),
                    ("АСМБ Бургас", "АСМБ Бургас"),
                    ("АСМБ Плевен", "АСМБ Плевен"),
                    ("АСМБ Стара Загора", "АСМБ Стара Загора"),
                ],
                default="АСМБ СУ",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="committee",
            field=models.CharField(
                choices=[
                    ("Scope", "Scope"),
                    ("Scora", "Scora"),
                    ("Score", "Score"),
                    ("Scome", "Scome"),
                    ("Scoph", "Scoph"),
                    ("Scopr", "Scopr"),
                ],
                default="Scora",
                max_length=100,
            ),
        ),
    ]
