# Generated by Django 5.1.6 on 2025-03-20 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_appstudent_can_approve_events"),
        ("reports", "0003_remove_eventreport_organizers_eventreport_organizers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventreport",
            name="prepared",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prepared",
                to="accounts.profile",
            ),
        ),
    ]
