# Generated by Django 5.1.6 on 2025-03-20 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_appstudent_can_approve_events"),
        ("reports", "0004_alter_eventreport_prepared"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="eventreport",
            name="users",
        ),
        migrations.RemoveField(
            model_name="eventreport",
            name="attended",
        ),
        migrations.AlterField(
            model_name="eventreport",
            name="organizers",
            field=models.ManyToManyField(
                related_name="organized_events", to="accounts.profile"
            ),
        ),
        migrations.RemoveField(
            model_name="eventreport",
            name="participated_actively",
        ),
        migrations.AlterField(
            model_name="eventreport",
            name="prepared",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="prepared_reports",
                to="accounts.profile",
            ),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="attended",
            field=models.ManyToManyField(
                blank=True, related_name="attended_events", to="accounts.profile"
            ),
        ),
        migrations.AddField(
            model_name="eventreport",
            name="participated_actively",
            field=models.ManyToManyField(
                blank=True, related_name="active_participants", to="accounts.profile"
            ),
        ),
    ]
